version: "3.7"

services:
  web:
    image: dezorgon/support-service
    command: sh entrypoint.prod.sh
    volumes:
      - static_web:/app/static
      - media_web:/app/media
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
      - celery

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file: .env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - static_web:/app/static
      - media_web:/app/media
    depends_on:
      - web

  celery:
    image: dezorgon/support-service
    command: celery --app support worker -l info
    env_file: .env
    depends_on:
      - redis

  flower:
    image: dezorgon/support-service
    command: sh ./flower_entrypoint.sh
    env_file: .env
    ports:
      - 5555:5555
    depends_on:
      - web
      - redis

  redis:
    image: redis:alpine
    expose:
      - 6379


volumes:
  static_web:
  media_web:
  postgres_db: