version: "3.7"

services:
  web:
    image: "support-service"
    build: ./app
    command: sh entrypoint.sh
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
      - celery

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file: .env
    expose:
      - 5432

  celery:
    image: "celery-consumer"
    build: ./app
    command: celery --app support worker -l info
    env_file: .env
    depends_on:
      - redis

  flower:
    build: ./app
    command: sh ./flower_entrypoint.sh
    env_file: .env
    ports:
      - 5555:5555
    depends_on:
      - web
      - redis

  redis:
    image: redis:alpine
    expose:
      - 6379


volumes:
  postgres_db: